(in-package :moonli)

(define-moonli-infix-macro binding-arrows:->)

(def-test binding-arrows:-> (infix-expression)
  (:lisp (binding-arrows:-> t (format "hello"))
   :moonli "t -> format(\"hello\")")
  (:lisp (or (binding-arrows:-> t (identity)) 42)
   :moonli "t -> identity() or 42")
  (:lisp (and (binding-arrows:-> t (identity)) 42)
   :moonli "t -> identity() and 42")
  (:lisp (and (binding-arrows:-> t (identity)) (- 42))
   :moonli "t -> identity() and - 42")
  (:lisp (binding-arrows:-> -2 (add 3))
   :moonli "-2 -> add(3)")
  (:lisp (binding-arrows:-> (- (+ 3 4)) (add 3))
   :moonli "- (3 + 4) -> add(3)")
  (:lisp (expt (binding-arrows:-> (- 4) (add 3)) 2)
   :moonli "- 4 -> add(3) ^ 2"))
