on: [push, pull_request, workflow_dispatch]

jobs:

  build:

    name: ${{ matrix.runner_os[0] }}

    strategy:
      matrix:
        lisp: [sbcl_static]
        runner_os: [
          [ubuntu-24.04, linux],
          [ubuntu-24.04-arm, linux],
          [macos-latest, darwin],
          [macos-15-intel, darwin]
        ]
    runs-on: ${{ matrix.runner_os[0] }}

    defaults:
      run:
        shell: bash

    steps:

    - uses: actions/checkout@v2

    - name: Update $PATH
      run: |
        echo $PATH
        echo "PATH=$HOME/bin:$PATH" >> $GITHUB_ENV

    - name: Check $PATH
      run: echo $PATH

    - name: Add $CORE, $REPL_CORE, $CIEL_CORE
      run: |
        echo "CORE=moonli-${{ github.ref_name }}.${{ matrix.runner_os[1] }}.$(uname -m)" >> $GITHUB_ENV
        echo "REPL_CORE=moonli-${{ github.ref_name }}.repl.${{ matrix.runner_os[1] }}.$(uname -m)" >> $GITHUB_ENV
        echo "CIEL_CORE=moonli-${{ github.ref_name }}.ciel.${{ matrix.runner_os[1] }}.$(uname -m)" >> $GITHUB_ENV

    - name: Download implementation
      env:
        LISP: ${{ matrix.lisp }}
        OS: ${{ matrix.runner_os[1] }}
      run: |
        pwd
        ls -l
        case $(uname -m) in
            x86_64) ARCH="x86-64" ;;
            arm64|aarch64) ARCH="arm64";;
            *) ARCH=$(uname -m) ;;
        esac
        echo "ARCH=${ARCH}" >> ${GITHUB_ENV}
        echo "OS=${OS}" >> ${GITHUB_ENV}
        bash --version
        bash <(curl -s https://raw.githubusercontent.com/digikar99/lisp-travis-lite/master/run.sh)

    - name: Download download-dependencies
      run: |
        git clone https://github.com/digikar99/download-dependencies $HOME/quicklisp/local-projects/download-dependencies

    - name: Download dependencies
      run: |
        cl --eval '(ql:quickload "download-dependencies")' \
           --eval '(in-package :download-dependencies)' \
           --eval '(push #P"./" ql:*local-project-directories*)' \
           --eval '(let ((*dependencies-home* (second ql:*local-project-directories*))) (ensure-system "moonli/repl"))'
        ls $HOME/quicklisp/local-projects/

    - name: Compile isocline
      run: |
        pwd
        cd $HOME/quicklisp/local-projects/cl-isocline/isocline
        mkdir -p build/release
        cd build/release
        cmake ../..
        cmake --build .

    - name: Install libssl libtls
      run: |
        if [ "$OS" == "linux" ]; then
            sudo apt install -y openssl libssl-dev libtls-dev atool
        elif [ "$OS" == "darwin" ]; then
            brew install openssl libretls atool
        fi

    - name: Statically link against libisocline + libcrypto, libssl, libtls
      run: |
        case ${OS} in
            linux) SYS_LIBDIR="/usr/lib/" ;;
            darwin) SYS_LIBDIR="$(brew --prefix)" ;;
        esac

        LIBCRYPTO=$(find $SYS_LIBDIR -name "libcrypto.a" | head -1)
        LIBSSL=$(find $SYS_LIBDIR -name "libssl.a" | head -1)
        LIBTLS=$(find $SYS_LIBDIR -name "libtls.a" | head -1)
        LIBISOCLINE="$HOME/quicklisp/local-projects/cl-isocline/isocline/build/release/libisocline.a"

        if [ "$OS" == "linux" ]; then
            SBCL_DIR="/home/runner/sbcl-2.6.6+r00-$ARCH-$OS"
            export WHOLE_ARCHIVES="-Wl,--whole-archive $LIBCRYPTO $LIBSSL $LIBTLS $LIBISOCLINE"
        elif [ "$OS" == "darwin" ]; then
            SBCL_DIR="/Users/runner/sbcl-2.6.6+r00-$ARCH-$OS"
            # -force_load only works on one library at a time
            export WHOLE_ARCHIVES="-Wl,-force_load $LIBCRYPTO -Wl,-force_load $LIBSSL -Wl $LIBTLS -Wl,-force_load $LIBISOCLINE"
        fi

        cd "$SBCL_DIR"
        make -C "src/runtime" -f binaries.mk sbcl.extras
        mv "src/runtime/sbcl.extras" "src/runtime/sbcl"
        echo "SBCL_DIR=${SBCL_DIR}" >> ${GITHUB_ENV}

    ## Below steps are for dumping and uploading

    - name: Prepare moonli
      run: |
        cl --eval '(push "./" ql:*local-project-directories*)' \
           --eval '(ql:quickload "moonli")' \
           --eval "(asdf:make :moonli)"
        mv moonli ${{ env.CORE }}.bin


    - name: Upload moonli
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.CORE }}.bin
        path: ${{ env.CORE }}.bin


    - name: Publish moonli
      if: startsWith(github.ref, 'refs/tags/')
      uses: SierraSoftworks/gh-releases@v1.0.4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        overwrite: 'true'
        files: ${{ env.CORE }}.bin


    - name: Prepare moonli-repl
      run: |
        cl --eval '(push "./" ql:*local-project-directories*)' \
           --eval '(ql:quickload "moonli/repl")' \
           --eval "(cffi:close-foreign-library 'isocline::libisocline)" \
           --eval "(asdf:make :moonli/repl)"
        mv moonli.repl ${{ env.REPL_CORE }}.bin


    - name: Upload moonli-repl
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.REPL_CORE }}.bin
        path: ${{ env.REPL_CORE }}.bin


    - name: Publish moonli-repl
      if: startsWith(github.ref, 'refs/tags/')
      uses: SierraSoftworks/gh-releases@v1.0.4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        overwrite: 'true'
        files: ${{ env.REPL_CORE }}.bin


    - name: Install ultralisp
      run: cl --eval '(ql-dist:install-dist "http://dist.ultralisp.org/" :prompt nil)'


    - name: Prepare moonli-ciel
      if: startsWith(github.ref, 'refs/tags/')
      continue-on-error: true
      run: |
        cl --eval '(push "./" ql:*local-project-directories*)' \
            --eval '(ql:quickload "moonli/ciel")' \
            --eval "(cffi:close-foreign-library 'isocline::libisocline)" \            
            --eval '(asdf:make "moonli/ciel")'
        mv moonli.ciel ${{ env.CIEL_CORE }}.bin


    - name: Upload moonli-ciel
      if: startsWith(github.ref, 'refs/tags/')
      continue-on-error: true
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.CIEL_CORE }}.bin
        path: ${{ env.CIEL_CORE }}.bin


    - name: Publish moonli-ciel
      if: startsWith(github.ref, 'refs/tags/')
      continue-on-error: true
      uses: SierraSoftworks/gh-releases@v1.0.4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        overwrite: 'true'
        files: ${{ env.CIEL_CORE }}.bin
